ahoyapi: v2
commands:
  deploy:
    usage: Deploy the site using ahoy
    cmd: |
      BRANCH=$1
      MESSAGE=$2
      REPO="git@github.com:wi-tec/tec-testing.git"
      CLONEFOLDER=`cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 12 | head -n 1`
      git clone --branch $BRANCH $REPO $CLONEFOLDER || git clone $REPO $CLONEFOLDER
      cd $CLONEFOLDER
      git branch $BRANCH ; git checkout $BRANCH
      shopt -s extglob
      rm -rf ./!(.git|.|..)
      cd ../
      cp -r build $CLONEFOLDER/
      mv $CLONEFOLDER/build/* $CLONEFOLDER
      rmdir $CLONEFOLDER/build
      cd $CLONEFOLDER
      git add --all .
      git commit -m "$MESSAGE"
      git push origin $BRANCH
      cd ../
      rm -rf $CLONEFOLDER
